# Generated by Django 3.2 on 2021-05-12 11:43

import datetime
from django.db import migrations, models
import shortuuidfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='customerentry',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, default=uuid.uuid4, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('Customername', models.CharField(default='user', max_length=50)),
                ('Receivedate', models.DateField(default=datetime.datetime(2021, 5, 12, 11, 43, 16, 794031))),
                ('Deliverydate', models.DateField(default=datetime.datetime(2021, 5, 12, 11, 43, 16, 794058))),
                ('jobpending', models.CharField(max_length=20)),
                ('Email', models.CharField(default='Trubotattend@gmail.com', max_length=30)),
                ('devicebrand', models.CharField(default='I-Phone', max_length=10)),
                ('model', models.CharField(default='I-Phones', max_length=10)),
                ('imei', models.CharField(max_length=20)),
                ('devicecolour', models.CharField(default='Black', max_length=10)),
                ('providerinfo', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('fault', models.CharField(default='Error', max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('power', models.BooleanField(default=False)),
                ('charging', models.BooleanField(default=False)),
                ('display', models.BooleanField(default=False)),
                ('camera', models.BooleanField(default=False)),
                ('battery', models.BooleanField(default=False)),
                ('pictures', models.ImageField(blank=True, upload_to='device_images')),
                ('others', models.TextField(max_length=200)),
                ('parts', models.TextField(default='NOTHING YET', max_length=120)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mobilemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicename', models.CharField(max_length=100)),
            ],
        ),
    ]
