# Generated by Django 3.2 on 2021-05-12 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerentry',
            name='Deliverydate',
            field=models.DateField(default=datetime.datetime(2021, 5, 12, 11, 43, 35, 779122)),
        ),
        migrations.AlterField(
            model_name='customerentry',
            name='Receivedate',
            field=models.DateField(default=datetime.datetime(2021, 5, 12, 11, 43, 35, 779094)),
        ),
    ]
