# Generated by Django 3.2 on 2021-05-24 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_auto_20210512_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerentry',
            name='Deliverydate',
            field=models.DateField(default=datetime.datetime(2021, 5, 24, 18, 36, 24, 66991)),
        ),
        migrations.AlterField(
            model_name='customerentry',
            name='Receivedate',
            field=models.DateField(default=datetime.datetime(2021, 5, 24, 18, 36, 24, 66957)),
        ),
    ]
